name: thewildandy
favicon: null
layout_spectrum: 0.8349054048303515
typography_spectrum: 0.34681622264906764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06539329537190497
  lightness: 0.9673411990515888
  saturation: 0.99470318807289
  rhythmicContrast: 0.5257630699779838
purpose: []
