name: thewildandy
favicon: null
layout_spectrum: 0.33979
typography_spectrum: 0.89339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefffa'
    - '#40445f'
    - '#d7cdcc'
    - '#777181'
    - '#aea3ad'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.99470318807289
  rhythmicContrast: 0.5
purpose: []
